import sword from '../../assets/equipment/icons/sword.png';
import bow from '../../assets/equipment/icons/bow.png';
import staff from '../../assets/equipment/icons/staff.png';
import chest from '../../assets/equipment/icons/armor.png';
import helmet from '../../assets/equipment/icons/helmet.png';
import legs from '../../assets/equipment/icons/legs.png';
import boots from '../../assets/equipment/icons/boots.png';
import amulet from '../../assets/equipment/icons/amulet.png';
import ring from '../../assets/equipment/icons/ring.png';
import dodge from '../../assets/ui/skills/dodge.png';
import whirlwind from '../../assets/ui/skills/whirlwind.png';
import slam from '../../assets/ui/skills/seismic-slam.png';
import multishot from '../../assets/ui/skills/multishot.png';
import rain from '../../assets/ui/skills/arrow-rain.png';
import bind from '../../assets/ui/skills/arcane-bind.svg';
import echoes from '../../assets/ui/skills/arcane-echoes.svg';
import type { ItemKind } from '../data/equipment';
import type { AdvancedSkillId } from '../data/advancedSkills';
export const ITEM_ICONS: Record<ItemKind, string> = { sword, bow, staff, helmet, chest, legs, boots, amulet, ring };
export const DODGE_ICON = dodge;
export const SKILL_ICONS: Record<AdvancedSkillId, string> = { whirlwind, 'seismic-slam': slam, multishot, 'arrow-rain': rain, 'arcane-bind': bind, 'arcane-echoes': echoes };
